version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-docker-postgres
    env_file:
      - .env
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - db
      - cache
    volumes:
      - ./src:/app/src

  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    container_name: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - ${DB_PORT}:${DB_PORT}

  cache:
    image: redis:6
    env_file:
      - .env
    ports:
      - 6379:6379

  redisinsight:
    image: redislabs/redisinsight
    ports:
      - "8001:8001"    

volumes:
  pgdata: