version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-docker-postgres
    env_file:
      - .env
    ports:
      - '8000:8000'
    depends_on:
      - db
    volumes:
      - ./src:/app/src

  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=authDB
      - POSTGRES_USER=auth
      - POSTGRES_PASSWORD=auth
    container_name: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  pgdata: